const rolePermissions = {
    'CREATE_INSTANT_INVITE': 'Create instant invite',
    'KICK_MEMBERS': 'Kick members',
    'BAN_MEMBERS': 'Ban members',
    'ADMINISTRATOR': 'Administrator (has all permissions)',
    'MANAGE_CHANNELS': 'Manage channels (edit, create, delete)',
    'MANAGE_GUILD': 'Manage server (edit the guild information, region, etc.)',
    'ADD_REACTIONS': 'Add reactions (add new reactions to messages)',
    'VIEW_AUDIT_LOG': 'View audit log',
    'PRIORITY_SPEAKER': 'Priority speaker',
    'STREAM': 'Stream',
    'VIEW_CHANNEL': 'View channel',
    'SEND_MESSAGES': 'Send messages',
    'SEND_TTS_MESSAGES': 'Send TTS messages',
    'MANAGE_MESSAGES': 'Manage messages (delete messages and reactions)',
    'EMBED_LINKS': 'Embed links (links posted will have a preview embedded)',
    'ATTACH_FILES': 'Attach files',
    'READ_MESSAGE_HISTORY': 'Read message history (view messages that were posted prior to opening Discord)',
    'MENTION_EVERYONE': 'Mention everyone',
    'USE_EXTERNAL_EMOJIS': 'Use external emojis (use emojis from different guilds)',
    'VIEW_GUILD_INSIGHTS': 'View guild insights',
    'CONNECT': 'Connect (connect to a voice channel)',
    'SPEAK': 'Speak (speak in a voice channel)',
    'MUTE_MEMBERS': 'Mute members (mute members in a voice channel)',
    'DEAFEN_MEMBERS': 'Deafen members (deafen members in a voice channel)',
    'MOVE_MEMBERS': 'Move members (move members between voice channels)',
    'USE_VAD': 'Use voice activity (use voice activity detection)',
    'CHANGE_NICKNAME': 'Change nickname',
    'MANAGE_NICKNAMES': 'Manage nicknames (change other members nicknames)',
    'MANAGE_ROLES': 'Manage roles (create, edit, delete roles)',
    'MANAGE_WEBHOOKS': 'Manage webhooks (create, edit, delete webhooks)',
    'MANAGE_EMOJIS_AND_STICKERS': 'Manage emojis and stickers',
    'USE_APPLICATION_COMMANDS': 'Use application commands',
    'REQUEST_TO_SPEAK': 'Request to speak',
    'MANAGE_EVENTS': 'Manage events',
    'MANAGE_THREADS': 'Manage threads',
    'USE_PUBLIC_THREADS': 'Use public threads',
    'CREATE_PUBLIC_THREADS': 'Create public threads',
    'USE_PRIVATE_THREADS': 'Use private threads',
    'CREATE_PRIVATE_THREADS': 'Create private threads',
    'USE_EXTERNAL_STICKERS': 'Use external stickers',
    'SEND_MESSAGES_IN_THREADS': 'Send messages in threads',
    'START_EMBEDDED_ACTIVITIES': 'Start embedded activities',
    'MODERATE_MEMBERS': 'Moderate members',
}

module.exports = {
    rolePermissions,
}